require('dotenv').config()

console.log(process.env.INLINE_COMMENTS)
console.log(process.env.INLINE_COMMENTS_SINGLE_QUOTES)
console.log(process.env.INLINE_COMMENTS_DOUBLE_QUOTES)
console.log(process.env.INLINE_COMMENTS_BACKTICKS)
console.log(process.env.INLINE_COMMENTS_SPACE)
console.log(process.env.DB_PASSWORD)
console.log(process.env.SECURE_TOKEN)
console.log(process.env.KEY1)
console.log(process.env.KEY2)
console.log(process.env.KEY3)
