var dotenv = require('dotenv')
var dotenvExpand = require('dotenv-expand')

var myEnv = dotenv.config()
dotenvExpand.expand(myEnv)

console.log(process.env.PASSWORD)
console.log(process.env.DB_PASS)
console.log(process.env.INLINE_COMMENTS)
console.log(process.env.INLINE_COMMENTS_SINGLE_QUOTES)
console.log(process.env.INLINE_COMMENTS_DOUBLE_QUOTES)
console.log(process.env.INLINE_COMMENTS_BACKTICKS)
console.log(process.env.INLINE_COMMENTS_SPACE)
console.log(process.env.DB_PASSWORD)
console.log(process.env.SECURE_TOKEN)
